// <auto-generated />
using Labb_4___API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb_4___API.Migrations
{
    [DbContext(typeof(Labb4DbContext))]
    [Migration("20220417185321_test4")]
    partial class test4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb_4___API.Models.Hobby", b =>
                {
                    b.Property<int>("HobbyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HobbyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HobbyID");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            HobbyID = 1,
                            HobbyDescription = "Cooking and preparing food.",
                            HobbyName = "Cooking"
                        },
                        new
                        {
                            HobbyID = 2,
                            HobbyDescription = "Watching and analysing movies.",
                            HobbyName = "Movies"
                        },
                        new
                        {
                            HobbyID = 3,
                            HobbyDescription = "Creating and modifying computer programs.",
                            HobbyName = "Programming"
                        },
                        new
                        {
                            HobbyID = 4,
                            HobbyDescription = "Playing chess.",
                            HobbyName = "Chess"
                        });
                });

            modelBuilder.Entity("Labb_4___API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserAge")
                        .HasColumnType("int");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserPhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            UserAge = 55,
                            UserFirstName = "Paul",
                            UserLastName = "Foster",
                            UserPhoneNumber = 4608000
                        },
                        new
                        {
                            UserID = 2,
                            UserAge = 25,
                            UserFirstName = "Daniel",
                            UserLastName = "Gyrén",
                            UserPhoneNumber = 939314
                        },
                        new
                        {
                            UserID = 3,
                            UserAge = 36,
                            UserFirstName = "Tobias",
                            UserLastName = "L",
                            UserPhoneNumber = 3827202
                        },
                        new
                        {
                            UserID = 4,
                            UserAge = 32,
                            UserFirstName = "Anas",
                            UserLastName = "A",
                            UserPhoneNumber = 18456759
                        },
                        new
                        {
                            UserID = 5,
                            UserAge = 39,
                            UserFirstName = "Alexandra",
                            UserLastName = "Anderson",
                            UserPhoneNumber = 69438204
                        });
                });

            modelBuilder.Entity("Labb_4___API.Models.Website", b =>
                {
                    b.Property<int>("WebsiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HobbyID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WebsiteID");

                    b.HasIndex("HobbyID");

                    b.HasIndex("UserID");

                    b.ToTable("Websites");

                    b.HasData(
                        new
                        {
                            WebsiteID = 1,
                            HobbyID = 1,
                            UserID = 1,
                            WebsiteLink = "https://www.Food.com/"
                        },
                        new
                        {
                            WebsiteID = 2,
                            HobbyID = 2,
                            UserID = 2,
                            WebsiteLink = "https://www.imdb.com/"
                        },
                        new
                        {
                            WebsiteID = 3,
                            HobbyID = 3,
                            UserID = 3,
                            WebsiteLink = "https://docs.microsoft.com/en-us/dotnet/csharp/"
                        },
                        new
                        {
                            WebsiteID = 4,
                            HobbyID = 3,
                            UserID = 4,
                            WebsiteLink = "https://docs.microsoft.com/en-us/dotnet/csharp/"
                        },
                        new
                        {
                            WebsiteID = 5,
                            HobbyID = 4,
                            UserID = 5,
                            WebsiteLink = "https://www.chess.com/"
                        });
                });

            modelBuilder.Entity("Labb_4___API.Models.Website", b =>
                {
                    b.HasOne("Labb_4___API.Models.Hobby", "Hobby")
                        .WithMany("Websites")
                        .HasForeignKey("HobbyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_4___API.Models.User", "User")
                        .WithMany("Websites")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
